name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: expo-app/package-lock.json

      - name: Install Expo CLI
        run: npm install expo-cli
        working-directory: expo-app


      - name: Install dependencies
        run: npm install
        working-directory: expo-app

      - name: Run Jest Tests with Coverage
        run: npx jest --coverage --ci
        working-directory: expo-app

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: expo-app/coverage/lcov.info
          fail_ci_if_error: true
          verbose: true

      - name: Start Expo Server and Wait
        run: |
          npx expo start --web &
          sleep 20
        working-directory: expo-app
        timeout-minutes: 5

      - name: Stop Expo Server
        if: always()
        run: pkill -f "expo start"


      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=goldendoodle-team
            -Dsonar.projectKey=alexsmags_GoldenDoodle
            -Dsonar.python.coverage.reportPaths=coverage.xml
