name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: expo-app/package-lock.json
          
      - name: Install Expo CLI
        run: npm install expo-cli
        working-directory: expo-app
        
      - name: Install Dependencies
        run: npm install
        working-directory: expo-app

      - name: Install Google Sign-In
        run: npm install @react-native-google-signin/google-signin
        working-directory: expo-app

  jest-tests-and-Sonar:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: expo-app/package-lock.json

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-cache-${{ runner.os }}-${{ hashFiles('expo-app/package-lock.json') }}
          restore-keys: |
            node-cache-${{ runner.os }}-
  
      - name: Install Dependencies
        run: |
          npm install
          npm install --save-dev jest-expo
        working-directory: expo-app
  
      - name: Run Jest Tests with Coverage
        run: |
          npx jest --coverage --ci --passWithNoTests
        working-directory: expo-app
  
      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: expo-app/coverage/lcov.info
          fail_ci_if_error: true
          verbose: true

      - name: List expo-app directory
        run: |
          echo "Listing contents of the expo-app directory..."
          ls -R expo-app/

          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        with:
          args: >
            -Dsonar.organization=goldendoodle-team
            -Dsonar.projectKey=alexsmags_GoldenDoodle
            -Dsonar.sources=expo-app
            -Dsonar.test.inclusions="expo-app/**/__tests__/**/*.{js,ts,tsx}"
            -Dsonar.tests=expo-app
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.javascript.lcov.reportPaths=expo-app/coverage/lcov-report/lcov-report.json  

  deploy:
    needs: [jest-tests-and-Sonar]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Add deployment steps here
