name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: expo-app/package-lock.json

      - name: Install Expo CLI
        run: npm install expo-cli
        working-directory: expo-app


      - name: Install dependencies
        run: npm install
        working-directory: expo-app

      - name: Start Expo Server and Wait
        run: |
          npx expo start --web &
          sleep 20
        working-directory: expo-app
        timeout-minutes: 5

      - name: Run Unit Tests
        run: npm test -- --coverage

      - name: Run Integration Tests
        run: npm run test:integration

      - name: Run End-to-End Tests
        run: npm run test:e2e

      - name: Stop Expo Server
        if: always()
        run: pkill -f "expo start"
