name: Run Maestro Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  maestro-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Change Directory to expo-app
        run: cd expo-app

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      
      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Verify Installation
        run: maestro --version

      - name: Install Android SDK
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y lib32stdc++6 lib32z1
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/cmdline-tools
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/tools
          mv $HOME/cmdline-tools/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/tools/
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
          yes | sdkmanager --licenses >/dev/null
          sdkmanager --install 'build-tools;35.0.0' platform-tools 'platforms;android-30' >/dev/null

      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          script: echo "Android Emulator is Ready"

      - name: Install dependencies
        run: npm install

      - name: Start Expo Server 
        run: 
          npx expo start -a

      - name: Wait for Expo to Start
        run: sleep 60  # Wait for Expo to fully boot

      - name: Run Maestro Tests
        run: maestro test maestro-tests/index-test.yaml

      - name: Upload Maestro Test Reports (if needed)
        uses: actions/upload-artifact@v4
        with:
          name: maestro-test-reports
          path: maestro-tests/reports/