name: Run Maestro Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  maestro-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java (Required for ADB)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          script: echo "Android Emulator is Ready"

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Verify Installation
        run: maestro --version

      - name: Start Expo Server
        run: |
          npm install -g expo-cli
          npm install
          npx expo start --no-interactive &

      - name: Wait for Expo to Start
        run: sleep 30  # Wait for Expo to fully boot

      - name: Run Maestro Tests
        run: maestro test maestro-tests/index-test.yaml

      - name: Upload Maestro Test Reports (if needed)
        uses: actions/upload-artifact@v3
        with:
          name: maestro-test-reports
          path: maestro-tests/reports/
