name: Run Maestro Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  maestro-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Change Directory to expo-app
        run: cd expo-app

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      
      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Verify Installation
        run: maestro --version

      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          script: echo "Android Emulator is Ready"

      - name: Start Expo Server
        run: |
          npm install
          npx expo start -a

      - name: Wait for Expo to Start
        run: sleep 60  # Wait for Expo to fully boot

      - name: Run Maestro Tests
        run: maestro test maestro-tests/index-test.yaml

      - name: Upload Maestro Test Reports (if needed)
        uses: actions/upload-artifact@v4
        with:
          name: maestro-test-reports
          path: maestro-tests/reports/
